# Generated by Django 4.1.2 on 2023-01-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMDAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonsalebill',
            name='label_code',
        ),
        migrations.RemoveField(
            model_name='salebill',
            name='label_code',
        ),
    ]
