# Generated by Django 4.1.2 on 2022-12-22 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IMDAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonstock',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMDAPP.noncategory'),
        ),
        migrations.AlterField(
            model_name='nonstock',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMDAPP.nondescription'),
        ),
        migrations.AlterField(
            model_name='nonstock',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMDAPP.nonsubcategory'),
        ),
    ]
