# Generated by Django 4.1.2 on 2022-12-28 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMDAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonsalebilldetails',
            name='total',
        ),
        migrations.RemoveField(
            model_name='nonsaleitem',
            name='perprice',
        ),
        migrations.RemoveField(
            model_name='nonsaleitem',
            name='totalprice',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='total',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='perprice',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='totalprice',
        ),
    ]
