# Generated by Django 4.1.2 on 2023-01-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMDAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='consumer',
            table='Consumer',
        ),
        migrations.AlterModelTable(
            name='description',
            table='Description',
        ),
        migrations.AlterModelTable(
            name='inwardbilldetails',
            table='InwardBillDetails',
        ),
        migrations.AlterModelTable(
            name='noncategory',
            table='NonCategory',
        ),
        migrations.AlterModelTable(
            name='nondescription',
            table='NonDescription',
        ),
        migrations.AlterModelTable(
            name='noninwardbilldetails',
            table='NonInwardBillDetails',
        ),
        migrations.AlterModelTable(
            name='nonpurchasebill',
            table='NonPurchaseBill',
        ),
        migrations.AlterModelTable(
            name='nonpurchasebilldetails',
            table='NonPurchaseBillDetails',
        ),
        migrations.AlterModelTable(
            name='nonpurchaseitem',
            table='NonPurchaseItem',
        ),
        migrations.AlterModelTable(
            name='nonsalebill',
            table='NonSaleBill',
        ),
        migrations.AlterModelTable(
            name='nonsalebilldetails',
            table='NonSaleBillDetails',
        ),
        migrations.AlterModelTable(
            name='nonsaleitem',
            table='NonSaleItem',
        ),
        migrations.AlterModelTable(
            name='nonstock',
            table='NonStock',
        ),
        migrations.AlterModelTable(
            name='nonsubcategory',
            table='NonSubcategory',
        ),
        migrations.AlterModelTable(
            name='purchasebill',
            table='PurchaseBill',
        ),
        migrations.AlterModelTable(
            name='purchasebilldetails',
            table='PurchaseBillDetails',
        ),
        migrations.AlterModelTable(
            name='purchaseitem',
            table='PurchaseItem',
        ),
        migrations.AlterModelTable(
            name='salebill',
            table='SaleBill',
        ),
        migrations.AlterModelTable(
            name='salebilldetails',
            table='SaleBillDetails',
        ),
        migrations.AlterModelTable(
            name='saleitem',
            table='SaleItem',
        ),
        migrations.AlterModelTable(
            name='stock',
            table='Stock',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='Subcategory',
        ),
        migrations.AlterModelTable(
            name='supplier',
            table='Supplier',
        ),
        migrations.AlterModelTable(
            name='unit',
            table='Unit',
        ),
    ]
