# Generated by Django 4.1.2 on 2023-02-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trs',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
