# Generated by Django 4.1.2 on 2023-01-06 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMDAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonsalebill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='nonsalebill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='nonsalebill',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='salebill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='salebill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='salebill',
            name='subcategory',
        ),
    ]
