# Generated by Django 4.1.2 on 2022-11-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trs',
            name='kdno',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trs',
            name='ref1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trs',
            name='ref2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trs',
            name='ref3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trs',
            name='sors_sink',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trs',
            name='unit_cost',
            field=models.CharField(max_length=255),
        ),
    ]
