# Generated by Django 4.1.2 on 2022-11-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='noncategory',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
