# Generated by Django 4.1.2 on 2022-11-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDAPP', '0002_alter_category_id_alter_noncategory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='noncategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
