# Generated by Django 4.1.2 on 2022-12-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDAPP', '0002_alter_supplier_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='phone',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
