# Generated by Django 4.1.2 on 2022-11-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDAPP', '0002_alter_trs_kdno_alter_trs_ref1_alter_trs_ref2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
    ]
