# Generated by Django 4.1.2 on 2023-01-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDAPP', '0002_remove_nonsalebill_label_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonstock',
            name='Mode_of_delivery',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Mode_of_delivery',
            field=models.CharField(max_length=50),
        ),
    ]
