# Generated by Django 4.1.2 on 2023-01-13 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDAPP', '0002_alter_consumer_name_alter_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='email',
            field=models.EmailField(max_length=100, validators=[django.core.validators.RegexValidator('[A-Za-z0-9.]@gmail[.]com', message='Enter a Valid Email Id')]),
        ),
    ]
