# Generated by Django 4.1.2 on 2022-12-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDAPP', '0003_alter_category_id_alter_noncategory_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonstock',
            name='unit',
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit',
            field=models.CharField(choices=[('mtr', 'mtr'), ('cm', 'cm'), ('mm', 'mm'), ('kg', 'kg'), ('gm', 'gm'), ('ltr', 'ltr'), ('sqmtr', 'sqmtr'), ('sqcm', 'sqcm'), ('cum', 'cum'), ('ream', 'ream'), ('doz', 'doz'), ('pkts', 'pkts'), ('pairs', 'pairs'), ('rolls', 'rolls'), ('inches', 'inches')], max_length=50),
        ),
    ]
