# Generated by Django 4.1.2 on 2023-01-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMDAPP', '0003_stock1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock1',
        ),
    ]
