# Generated by Django 4.1.2 on 2023-01-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDAPP', '0003_alter_nonstock_mode_of_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonsalebill',
            name='Mode_of_delivery',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='salebill',
            name='Mode_of_delivery',
            field=models.CharField(max_length=50),
        ),
    ]
