# Generated by Django 4.1.2 on 2022-12-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDAPP', '0003_alter_salebill_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonsalebill',
            name='gstin',
            field=models.CharField(max_length=15),
        ),
    ]
