# Generated by Django 4.1.2 on 2023-01-16 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IMDAPP', '0004_alter_consumer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock1',
            fields=[
                ('billno', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('Mode_of_delivery', models.CharField(max_length=50)),
                ('label_code', models.CharField(default='', max_length=20)),
                ('condition', models.CharField(choices=[('GOOD', 'GOOD'), ('TORN', 'TORN'), ('DAMAGED', 'DAMAGED')], max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('perprice', models.IntegerField(default=1)),
                ('totalprice', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMDAPP.category')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMDAPP.description')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMDAPP.consumer')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMDAPP.subcategory')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMDAPP.unit')),
            ],
        ),
    ]
