# Generated by Django 4.1.2 on 2022-12-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDAPP', '0004_remove_nonstock_unit_alter_stock_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trs',
            name='qty_trs',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
