# Generated by Django 4.1.2 on 2023-01-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDAPP', '0004_delete_stock1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonstock',
            name='label_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='label_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
