# Generated by Django 4.1.2 on 2022-12-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDAPP', '0007_alter_consumer_id_alter_supplier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
