# Generated by Django 4.1.2 on 2022-12-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDAPP', '0011_alter_nonstock_id_alter_stock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
